---
# this comment is a hack
version: '3'
services:
  guacamole:
    image: oznu/guacamole@sha256:6268b3a08d9b3d71e1f8edfd593af95f0e1082b5f3d8649321b45c64e182a3a4
    container_name: guacamole
    volumes:
      - /docker/docker-compose/guacamole/config:/config
      - /docker/docker-compose/guacamole/etc_guacamole:/etc/guacamole
    ports:
      - 8081:8080
    restart:  unless-stopped
    deploy:
      restart_policy:
        condition: on-failure
